default_context:
  project_name: 'techjobs'
  project_slug: 'techjobs'
  domain_main: 'techjobs.com'
  domain_staging: 'stag.techjobs.com'
  docker_swarm_stack_name_main: 'techjobs-com'
  docker_swarm_stack_name_staging: 'stag-techjobs-com'
  secret_key: '3a5d5866d55569774ecde60b490e02658829b3fd8b96c724eeb334e23ab7713a'
  first_superuser: 'admin@techjobs.com'
  first_superuser_password: '123456'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.techjobs.com", "https://stag.techjobs.com", "https://techjobs.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@techjobs.com'
  postgres_password: '123456'
  pgadmin_default_user: 'admin@techjobs.com'
  pgadmin_default_user_password: '123456'
  traefik_constraint_tag: 'techjobs.com'
  traefik_constraint_tag_staging: 'stag.techjobs.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:123456'
  sentry_dsn: ''
  docker_image_prefix: 'tj_'
  docker_image_backend: 'tj_backend'
  docker_image_celeryworker: 'tj_celeryworker'
  docker_image_frontend: 'tj_frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
