# Generated by Django 4.0 on 2022-01-05 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('CONTRACT_TYPE', 'Tipo de contratação'), ('EXPERIENCE', 'Experiência'), ('WORK_LOCATION', 'Local de Trabalho'), ('TECHNOLOGY', 'Tecnologia'), ('ROLE', 'Tipo de Cargo'), ('OTHER', 'Outras tags')], max_length=64)),
                ('show_in_options', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('source', models.CharField(choices=[('FORM', 'Preenchimento do formulário'), ('TWITTER', 'Bot do twitter'), ('OTHER', 'Chamada da API por outros')], max_length=32, verbose_name='Origem')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('company_name', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
                ('recruiter_name', models.CharField(max_length=255, verbose_name='Nome Recrutador(a)')),
                ('recruiter_contact_info', models.CharField(blank=True, max_length=255, verbose_name='Contato Recrutador(a)')),
                ('link', models.CharField(max_length=2048, unique=True, verbose_name='Link da vaga')),
                ('salary_from', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário a partir de')),
                ('salary_to', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário até')),
                ('current_status', models.CharField(choices=[('IN_EVALUATION', 'Em Avaliação'), ('CANCELLED', 'Cancelada'), ('APPROVED', 'Aprovada'), ('DISAPPROVED', 'Reprovada')], max_length=32, verbose_name='Status')),
                ('location', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Localidade')),
                ('tags', models.ManyToManyField(to='techjobs_app.JobTagModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('content', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techjobs_app.jobmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobAuditModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('from_status', models.CharField(choices=[('IN_EVALUATION', 'Em Avaliação'), ('CANCELLED', 'Cancelada'), ('APPROVED', 'Aprovada'), ('DISAPPROVED', 'Reprovada')], max_length=32, null=True, verbose_name='Do status')),
                ('to_status', models.CharField(choices=[('IN_EVALUATION', 'Em Avaliação'), ('CANCELLED', 'Cancelada'), ('APPROVED', 'Aprovada'), ('DISAPPROVED', 'Reprovada')], max_length=32, verbose_name='Para o status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BroadcastLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('type', models.CharField(choices=[('DISCORD', 'Discord'), ('EMAIL', 'Email')], max_length=32, verbose_name='Modal de envio')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('target', models.CharField(max_length=255, null=True, verbose_name='Alvos')),
                ('related_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='techjobs_app.jobmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
