# Generated by Django 4.0.1 on 2022-01-06 19:37

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='JobTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('CONTRACT_TYPE', 'Tipo de contratação'), ('EXPERIENCE', 'Experiência'), ('WORK_LOCATION', 'Local de Trabalho'), ('TECHNOLOGY', 'Tecnologia'), ('ROLE', 'Tipo de Cargo'), ('OTHER', 'Outras tags')], max_length=64)),
                ('show_in_options', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('source', models.CharField(choices=[('FORM', 'Preenchimento do formulário'), ('TWITTER', 'Bot do twitter'), ('OTHER', 'Chamada da API por outros')], max_length=32, verbose_name='Origem')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('company_name', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
                ('recruiter_name', models.CharField(max_length=255, verbose_name='Nome Recrutador(a)')),
                ('recruiter_contact_info', models.CharField(blank=True, max_length=255, verbose_name='Contato Recrutador(a)')),
                ('link', models.CharField(max_length=2048, unique=True, verbose_name='Link da vaga')),
                ('salary_from', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário a partir de')),
                ('salary_to', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário até')),
                ('current_status', models.CharField(choices=[('IN_EVALUATION', 'Em Avaliação'), ('CANCELLED', 'Cancelada'), ('APPROVED', 'Aprovada'), ('DISAPPROVED', 'Reprovada')], max_length=32, verbose_name='Status')),
                ('location', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Localidade')),
                ('tags', models.ManyToManyField(to='techjobs_app.JobTagModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('content', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techjobs_app.jobmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobAuditModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('from_status', models.CharField(choices=[('IN_EVALUATION', 'Em Avaliação'), ('CANCELLED', 'Cancelada'), ('APPROVED', 'Aprovada'), ('DISAPPROVED', 'Reprovada')], max_length=32, null=True, verbose_name='Do status')),
                ('to_status', models.CharField(choices=[('IN_EVALUATION', 'Em Avaliação'), ('CANCELLED', 'Cancelada'), ('APPROVED', 'Aprovada'), ('DISAPPROVED', 'Reprovada')], max_length=32, verbose_name='Para o status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BroadcastLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('type', models.CharField(choices=[('DISCORD', 'Discord'), ('EMAIL', 'Email')], max_length=32, verbose_name='Modal de envio')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('target', models.CharField(max_length=255, null=True, verbose_name='Alvos')),
                ('related_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='techjobs_app.jobmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
