# Generated by Django 4.0 on 2022-01-05 06:08

from django.db import migrations
from django.contrib.auth.models import Group, Permission

from collections.abc import Iterable


def initial_permission_groups(apps, schema_editor):
    Group = apps.get_model("techjobs_root", "Group")
    Permission = apps.get_model("techjobs_root", "Permission")
    CType = apps.get_model("techjobs_root", "ContentType")

    def get_permissions_for_models(
        models: Iterable[str], input_permissions=["create", "update", "delete", "view"]
    ):
        out = []
        for model in models:
            codenames = []
            for perm in input_permissions:
                codenames.append(perm + "_" + model)
            permissions = Permission.objects.filter(codename__in=codenames).all()
            for each_perm in permissions:
                out.append(each_perm)
        return out

    def create_group(name: str, permissions: Iterable):
        group = Group(name=name)
        group.permissions.set(permissions)
        group.save()
        return group

    reviewer_group = create_group(
        "Aprovador",
        get_permissions_for_models(
            ["jobmodel", "jobauditmodel", "jobcommentmodel", "jobtagmodel"],
        ),
    )
    manager_group = create_group("Administrador", get_permissions_for_models(["user"]))
    broadcaster_script_group = create_group(
        "Serviço de Envio",
        [
            get_permissions_for_models(["jobmodel"], ["view"]),
            get_permissions_for_models(["jobauditmodel", "broadcastlogmodel"]),
        ],
    )

    # job_ctype = CType.objects.get(app_label="techjobs_app", model="jobmodel")
    # broadcastlog_ctype = CType.objects.get(
    #     app_label="techjobs_app", model="broadcastinglogmodel"
    # )
    # jobaudit_ctype = CType.objects.get(
    #     app_label='techjobs_app', model='jobauditmodel'
    # )
    # jobcomment_ctype = CType.objects.get(
    #     app_label='techjobs_app', model='jobcommentmodel'
    # )
    # jobtag_ctype = CType.objects.get(
    #     app_label="techjobs_app", model="jobtagmodel"
    # )


class Migration(migrations.Migration):

    dependencies = [
        ("techjobs_app", "0001_initial"),
    ]

    operations = [migrations.RunPython(initial_permission_groups)]
